apiVersion: v1
kind: Service
metadata:
  name: telecom-api
spec:
  selector:
    app: telecom-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: telecom-dashboard
spec:
  selector:
    app: telecom-dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telecom-config
data:
  mlflow_uri: "http://mlflow-service:5000"
